# Generated by Django 4.2.3 on 2023-07-14 16:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0003_order_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="MonoSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("public_key", models.CharField(max_length=200)),
            ],
        ),
    ]
