# Generated by Django 4.2.3 on 2023-07-14 17:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0004_monosettings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="monosettings",
            name="public_key",
            field=models.CharField(max_length=1000),
        ),
    ]
